# Generated by Django 3.2.9 on 2022-06-07 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0002_todoitem_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
