# Generated by Django 3.2.9 on 2022-06-07 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0003_todoitem_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='email',
            field=models.EmailField(default='x', max_length=100),
            preserve_default=False,
        ),
    ]
