# Generated by Django 3.2.9 on 2022-06-07 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0004_todoitem_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='phone',
            field=models.CharField(default='x', max_length=100),
            preserve_default=False,
        ),
    ]
