# Generated by Django 3.2.9 on 2022-06-07 18:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0005_todoitem_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='birthday',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
