# Generated by Django 3.2.9 on 2022-06-07 18:48

from django.db import migrations, models
import todo_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0007_alter_todoitem_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='birthday',
            field=models.DateField(default=todo_app.models.one_week_hence),
        ),
    ]
