# Generated by Django 3.2.9 on 2022-06-07 18:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0008_alter_todoitem_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='birthday',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
