# Generated by Django 3.2.9 on 2022-06-07 19:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0009_alter_todoitem_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='birthday',
            field=models.DateField(default=datetime.date(2022, 6, 7)),
        ),
    ]
