# Generated by Django 3.2.9 on 2022-06-07 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0011_remove_todoitem_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todoitem',
            options={'ordering': ['title']},
        ),
    ]
