# Generated by Django 3.2.9 on 2022-06-10 16:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0013_remove_todoitem_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='birthday',
            field=models.DateField(default=datetime.date(2022, 6, 10)),
        ),
    ]
